# This is a basic workflow to help you get started with Actions
name: AKS Deployment

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - name: "Az CLI login"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: "Run checkout"
        uses: actions/checkout@v2

      - name: "Run login az"
        run: |
          az account set --subscription ca9482c7-87e7-4b26-8418-bc48a82240b5
          az aks get-credentials --resource-group azure-tp_group --name azure-tp --overwrite-existing
          kubectl config set-context --current --namespace=${{ secrets.K8S_NAMESPACE }}

      - name: "Run Azure CLI commands"
        run: |
          docker build -t devmptg.azurecr.io/mp-devops-app:${{ github.sha }} .
          az acr login --name devmptg 
          docker push devmptg.azurecr.io/mp-devops-app:${{ github.sha }}
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
